### ISSUE TITLE
Redox Wireless receiver LEDs not lighting up

### ISSUE THREAD

**Issue by Goldielocks** [mattdibi/redox-keyboard#93] opened 2021-03-25 15:51 UTC
I'm having an issue with the receiver: I can program it by header, but when I connect it to the Arduino Pro Micro, no lights appear. I've assembled several units at this point, since I ordered some redundant parts, and they all have the same behavior. If pin  validated the continuity (testing for shorts as well) but the lights still do not turn on.

I record a voltage drop over the LED/resistor as well, so it seems odd that nothing is visible. Do you have any thoughts?

**Comment by Goldielocks** [comment] 2021-03-25 16:39
https://photos.app.goo.gl/ZBaQ3kaNugr6mHov6
https://photos.app.goo.gl/jb4UTSCqM7cQC6G86

I've confirmed with Falba that their PCB's are behaving correctly. The above pictures are of one of the assembled boards.

**Comment by Goldielocks** [comment] 2021-03-25 17:38
Testing the voltage on my pins, it's becoming clear that none of them are reaching a sufficient low for current to pass. They seem to be floating. It's possible that the arduinos are no good. At least one of the ones I was testing with turned out to be the 3.3V Pro Micro

**Comment by mattdibi** [comment] 2021-03-25 19:47
> It's possible that the arduinos are no good. At least one of the ones I was testing with turned out to be the 3.3V Pro Micro

Yup. You should use 5V Pro Micros.

**Comment by Goldielocks** [comment] 2021-03-25 20:06
Sorry, this is not closed. The 5V Pro Micro has not solved my issue

**Comment by mattdibi** [comment] 2021-03-26 07:32
From #94 

>  I think I've confirmed that the problem is on the Arduino/QMK side of things. It's an arduino micro clone, but it's still using an Mega32U4-MU. Arduino IDE identifies it as a leondardo, which I understand is fairly common for micro clones.

Did you pinpoint the issue? What resistor values did you use for the LEDs? Does the receiver works (i.e. keystrokes are registered?) Does this happen for all the LEDs?

**Comment by Goldielocks** [comment] 2021-03-26 17:03
The issue hasn't been pinpointed, but at least one receiver is working. Only the first one appears to have been bricked, which led me down a bit of a goose chase. In fact I'm writing on it now. 

I'm referring to the LEDs on the receiver board. Now that it's transmitting, it appears that the bottom LEDs do function. I'm using the default configuration for the LED/resistor pairs. Red, Blue, Green, White in that order top to bottom. 330, 220, 330, 220.

**Comment by mattdibi** [comment] 2021-03-27 09:08
> I'm referring to the LEDs on the receiver board. Now that it's transmitting, it appears that the bottom LEDs do function. I'm using the default configuration for the LED/resistor pairs. Red, Blue, Green, White in that order top to bottom. 330, 220, 330, 220.

The LEDs light up when the layer is switched. To trigger a layer switch you need to press the following keys in the default keymap:

![redox-layout](https://user-images.githubusercontent.com/22748355/112715947-ca702680-8ee3-11eb-9ebc-48e676dc4b04.png)

Refer to [the default keymap ](https://github.com/qmk/qmk_firmware/blob/master/keyboards/redox_w/keymaps/default/keymap.c)for details.

Please note that the fourth LEDs is not mapped to any function in the default keymap and thus won't light up.

>  I'm using the default configuration for the LED/resistor pairs. Red, Blue, Green, White in that order top to bottom. 330, 220, 330, 220.

You should be good then.

**Comment by TheCatster** [comment] 2021-04-05 17:47
I am having similar issues, I am using the SparkFun Pro Micro. However, I do not have any LEDs lighting even after following this issue. I have checked the leads and all seems proper, and my reset button works, but the LEDs do nothing. Any ideas for that (or should I make a new issue)?

**Comment by mattdibi** [comment] 2021-04-05 18:43
@TheCatster At this point I’m suspecting something broke in QMK. If you burn the pre compiled QMK hex files available [here](https://github.com/mattdibi/redox-keyboard/tree/master/redox-w/firmware) do the LEDs light up? That file (`qmk_redox_w_default.hex`) was built using an older version of QMK and should work.

**Comment by TheCatster** [comment] 2021-04-05 19:07
I'll try it out as soon as I'm done flashing the left hand here. To add to your possible suspicion, I haven't actually tried your QMK file yet, I have only compiled my own keymaps!

**Comment by mattdibi** [comment] 2021-04-06 16:02
Just tested it with the latest version of QMK firmware. Everything is working fine.

@TheCatster If you can't connect the transmitters to the receiver the LEDs won't light up as they're triggered by key presses. You won't get keypresses until the firmware for the trasmitters MCUs, the firmware for the receiver MCU and the QMK firmware for the Arduino are all burned on their MCUs as described [here](https://github.com/mattdibi/redox-keyboard/tree/master/redox-w#firmware). If you still have issues, please open a new issue.

@Goldielocks Since I didn't receive any update I'm closing this. Feel free to reopen this if you still have issues.

**Closed by mattdibi** 2021-04-06 16:02 UTC
Labels: technical support

**Comment by tterrag1098** [comment] 2022-03-20 00:33
Hi, I'm currently running into this issue. I can only get the LEDs to work if I use the default firmware from the redox repository. If I try to compile it myself (using 0.15.25 due to https://github.com/qmk/qmk_firmware/issues/16553) everything seems to work fine *except* the LEDs on the arduino. Is there anything in QMK that could have changed to break this? Or a setting that needs to be changed from default?

**Comment by tterrag1098** [comment] 2022-03-20 00:43
Just to sanity check, I tried with the version of QMK that would have been latest at the time of your last comment, 0.12.32, and found the same behavior.

**Comment by tterrag1098** [comment] 2022-03-20 19:24
Okay, sorry for the triple post here, but I wanted to update you to say I found the solution.

The root cause is definitely that I am a noob, but I think there is a serious lack information here. It took me many hours to find that the LED behavior is implemented [in the keymap](https://github.com/qmk/qmk_firmware/blob/master/keyboards/redox_w/keymaps/default/keymap.c#L91-L109) at the very bottom. The very limited information about this I can find online never mentions this, and in fact seems to imply that it's built into the firmware.

All the guides to first time users creating their first firmware suggests to use the online configurator, which of course creates a keymap file from scratch, and won't have the above code in it. Is there no way this could be implemented into the keyboard-specific firmware code in QMK, rather than the keymap?

Again, sorry for all the comments about this, but I wanted to get all this info out there for others in the future, and in the hope it might be improved. Thank you for all your work on this keyboard, it really is great to use. This issue is minor in the grand scheme, after all.

**Comment by TheCatster** [comment] 2022-03-21 23:45
That's quite interesting. I actually gave up on the LED, thinking it was something I had done wrong (I guess in a way it was). This would be nice to get in the firmware, but as @tterrag1098 said it's a minor issue overall.

**Comment by tsxoxo** [comment] 2026-01-14 08:38
EDIT 1: Found [relevant code](https://github.com/qmk/qmk_firmware/blob/558ab18611665c3b447c27bac82fac2224eadaef/keyboards/redox_w/keymaps/default/keymap.c#L91) in default/keymap.c.
---
Still struggling with this: I want a simple layer indicator. LEDs on the dongle/receiver/arduino used to light up in different colors with the default keymap. After I changed the layout via the online QMK configurator and baked my own firmware the lightshow stopped. 

Info is extremely scarce and now the link to the default keymap is 404 and even that is not easy to google. Can anybody jot down the basic steps in a noob-friendly way? If I can get it to work I'd karmically repay the favor by documenting the process and doing a PR.

If y'all know where to find the default keymap or any keymap with a working LED-layer-indicator implementation, I'd be grateful for that too.
